spring:
  application:
    name: GroupPay
  datasource:
    url: jdbc:mysql://group-pay-bankofapis.e.aivencloud.com:10616/bank_of_apis?createDatabaseIfNotExist=true
    username: avnadmin
    password: AVNS_phRIoLjrR-0llqtiev_
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
      orm:
        jdbc:
          bind: TRACE

server:
  port: 8001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.0.69:8761/eureka}
  instance:
    hostname: 192.168.0.69
    prefer-ip-address: true

jwt:
  secret: a21f6cf93e1b7a924b7667f1d95c907ca6335ceb4012c3e717dfe5201aad7340

merchant:
  base-url: http://127.0.0.1:8002