spring:
  application:
    name: GroupPayMerchant
  datasource:
    url: jdbc:mysql://group-pay-bankofapis.e.aivencloud.com:10616/bankofapis?createDatabaseIfNotExist=true
    username: avnadmin
    password: AVNS_phRIoLjrR-0llqtiev_
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8002

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIodyudkhhhhbehhiuehuigvfxdt776e54

merchant:
  details:
    name: Boooking.com
    id: NWB001